import Head from "next/head";
import { styled } from "../stitches.config";

const Text = styled("p", {
  fontFamily: "$system",
  color: "$red",
  variants: {
    size: {
      1: {
        fontSize: "$1",
      },
      1.2: {
        fontSize: "$1.2",
      },
      1.4: {
        fontSize: "$1.4",
      },
    },
  },
});

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Text as="h1" size="1.4">
          Hello World
        </Text>
      </main>
    </div>
  );
}
